Web365/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web365Business.Front_End.IRepository;
using Web365Utility;

namespace Web365.Controllers
{
    public class LayoutController : Controller
    {
        private IArticleRepositoryFE _articleRepositoryFe;
        private IOtherRepositoryFE _orderRepositoryFe;
        private IVideoRepositoryFE _videoRepositoryFe;
        private IPictureRepositoryFE _pictureRepositoryFe;

        public LayoutController(IArticleRepositoryFE articleRepositoryFe, IOtherRepositoryFE orderRepositoryFe, IVideoRepositoryFE videoRepositoryFe, IPictureRepositoryFE pictureRepositoryFe)
        {
            _articleRepositoryFe = articleRepositoryFe;
            _orderRepositoryFe = orderRepositoryFe;
            _videoRepositoryFe = videoRepositoryFe;
            _pictureRepositoryFe = pictureRepositoryFe;
        }

        // GET: Layout
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuTop()
        {
            ViewData.Model = _orderRepositoryFe.GetServiceItems();
            return View();
        }

        public ActionResult Footer()
        {
            return View();
        }

        public ActionResult BookForm()
        {
            return View();
        }

        public ActionResult VideosAndPictures()
        {
            ViewData.Model = _pictureRepositoryFe.GetListByType((int)StaticEnum.ImageType.Library, string.Empty, 0,
                ConfigWeb.QuantityImageInLibrary);
            ViewBag.Video = _videoRepositoryFe.GetHomePageVideo();
            return View();
        }

        public ActionResult NewestNews()
        {
            ViewData.Model = _articleRepositoryFe.GetTopByType((int)StaticEnum.NewsType.News, 0,
                ConfigWeb.PageSizeNewestNews);
            return View();
        }

        public ActionResult MenuRight(bool? isPromotion)
        {
            ViewData.Model = _articleRepositoryFe.GetTopByType((int)StaticEnum.NewsType.FeedBack, 0, 100);
            //if (articleId.HasValue)
            //{
            //    ViewData["ListOtherNews"] = _articleRepositoryFe.GetOtherArticle((int)StaticEnum.NewsType.News,
            //        articleId.Value, 0,
            //        ConfigWeb.OtherNewsQuantity);
            //}
            //else
            //{
            ViewBag.IsPromotion = isPromotion == true;
            ViewData["ListOtherNews"] = _articleRepositoryFe.GetTopByType(
                isPromotion == true ? (int)StaticEnum.NewsType.Promotion : (int)StaticEnum.NewsType.News,
                0,
                ConfigWeb.OtherNewsQuantity);
            //}
            return View();
        }
    }
}

Web365/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web365Business.Front_End.IRepository;
using Web365Domain;
using Web365Utility;

namespace Web365.Controllers
{
    public class NewsController : Controller
    {
        private IArticleRepositoryFE _articleRepositoryFe;

        public NewsController(IArticleRepositoryFE article)
        {
            _articleRepositoryFe = article;
        }
        // GET: News
        public ActionResult Index(int? page)
        {
            ViewBag.Page = page ?? 1;
            return View();
        }

        public ActionResult ListNewestNews(int page)
        {
            ViewData.Model = _articleRepositoryFe.GetNewestNews((int)StaticEnum.NewsType.News, (page - 1) * ConfigWeb.PageSizeNews, ConfigWeb.PageSizeNews);
            return View();
        }

        public ActionResult NewsDetail(string nameascii)
        {
            ViewData.Model = _articleRepositoryFe.GetItemByNameAscii(nameascii);
            return View();
        }

        public ActionResult PromotionDetail(string nameascii)
        {
            ViewData.Model = _articleRepositoryFe.GetItemByNameAscii(nameascii);
            return View();
        }

        public ActionResult Promotion(int? page)
        {
            ViewBag.Page = page ?? 1;
            return View();
        }

        public ActionResult ListPromotion(int page)
        {
            ViewData.Model = _articleRepositoryFe
                .GetListByType((int)StaticEnum.NewsType.Promotion, string.Empty, (page - 1) * ConfigWeb.PageSizePromotion, ConfigWeb.PageSizePromotion);
            return View();
        }
    }
}

Web365/Views/News/Index.cshtml
@{
    ViewBag.Title = "Tin tức";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="sp-header-bot">
    <div class="container">
        <h1 class="sp-hbot-tit">Tin Tức</h1>
    </div>
</div>
<div class="sp-main">
    <div class="container">
        <div class="row">
            @Html.Action("ListNewestNews", "News", new {page = ViewBag.Page})
            <!--LEFT-->
            @Html.Action("MenuRight", "Layout")
            <!--RIGHT-->
        </div>
    </div>
</div>

Web365/Views/News/ListNewestNews.cshtml
@model Web365Models.ListArticleModel

<div class="col-sm-9 col-xs-12">
    <div class="sp-bread">
        <ul>
            <li><a href="/">Trang chủ</a></li>
            <li class="active"><a href="/tin-tuc" title="">Tin tức</a></li>
        </ul>
    </div>
    <div class="sp-listnews">
        @foreach (var item in Model.List)
        {
            <div class="sp-lnews-i">
                <div class="row">
                    <div class="col-xs-5">
                        <a class="sp-lnews-img" href="/tin-tuc/@Html.DisplayFor(modelItem => item.TitleAscii)" title="@Html.DisplayFor(modelItem => item.Title)">
                            <img src="@Web365Utility.Web365Utility.GetPathPicture(item.Picture.FileName)" alt="@Html.DisplayFor(modelItem => item.Title)" class="wow flipInX" />
                        </a>
                    </div>
                    <div class="col-xs-7">
                        <a class="sp-lnews-name" href="/tin-tuc/@Html.DisplayFor(modelItem => item.TitleAscii)" title="@Html.DisplayFor(modelItem => item.Title)">
                            <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
                        </a>
                        <div class="sp-lnews-dest">
                            @Html.Raw(item.Summary)
                        </div>
                        <p class="sp-lnews-vmore"><a href="/tin-tuc/@Html.DisplayFor(modelItem => item.TitleAscii)" title="@Html.DisplayFor(modelItem => item.Title)">CHI TIẾT ›</a>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>

    @Paging.Page(Model.total, string.IsNullOrEmpty(Request.QueryString["page"]) ? 1 : Int32.Parse(Request.QueryString["page"]), Web365Utility.ConfigWeb.PageSizeNews)
</div>

Web365/Views/News/ListPromotion.cshtml
@model Web365Models.ListArticleModel

<div class="col-sm-9 col-xs-12">
    <div class="sp-bread">
        <ul>
            <li><a href="/">Trang chủ</a></li>
            <li class="active"><a href="/khuyen-mai" title="">Khuyến mại</a></li>
        </ul>
    </div>
    <div class="sp-listnews">
        @foreach (var item in Model.List)
        {
            <div class="sp-lnews-i">
                <div class="row">
                    <div class="col-xs-5">
                        <a class="sp-lnews-img" href="/khuyen-mai/@Html.DisplayFor(modelItem => item.TitleAscii)" title="@Html.DisplayFor(modelItem => item.Title)">
                            <img src="@Web365Utility.Web365Utility.GetPathPicture(item.Picture.FileName)" alt="@Html.DisplayFor(modelItem => item.Title)" class="wow flipInX" />
                        </a>
                    </div>
                    <div class="col-xs-7">
                        <a class="sp-lnews-name" href="/khuyen-mai/@Html.DisplayFor(modelItem => item.TitleAscii)" title="@Html.DisplayFor(modelItem => item.Title)">
                            <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
                        </a>
                        <div class="sp-lnews-dest">
                            @Html.Raw(item.Summary)
                        </div>
                        <p class="sp-lnews-vmore">
                            <a href="/khuyen-mai/@Html.DisplayFor(modelItem => item.TitleAscii)" title="@Html.DisplayFor(modelItem => item.Title)">CHI TIẾT ›</a>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>

    @Paging.Page(Model.total, string.IsNullOrEmpty(Request.QueryString["page"]) ? 1 : Int32.Parse(Request.QueryString["page"]), Web365Utility.ConfigWeb.PageSizeNews)
</div>

Web365/Views/News/NewsDetail.cshtml
@using System.Globalization
@model Web365Domain.ArticleItem

@{ 
    ViewBag.Title = Model.SEOTitle;
    ViewBag.Description = Model.SEODescription;
    ViewBag.Keywords = Model.SEOKeyword;
    ViewBag.Image = Web365Utility.Web365Utility.GetPathPicture(Model.Picture.FileName);
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="sp-header-bot">
    <div class="container">
        <h1 class="sp-hbot-tit">Tin Tức</h1>
    </div>
</div>
<div class="sp-main">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-xs-12">
                <div class="sp-bread">
                    <ul>
                        <li><a href="/">Trang chủ</a></li>
                        <li class="active"><a href="/tin-tuc" title="Tin tức">Tin tức</a></li>
                    </ul>
                </div>
                <div class="sp-dtnews-main">
                    <h1 class="sp-dtnews-mname">@Model.Title</h1>
                    <p class="sp-dtnews-time">
                        @(Model.DateCreated != null
                                                    ? Model.DateCreated.Value.ToString("dd/MM/yyyy, hh:mm", CultureInfo.InvariantCulture)
                                                    : string.Empty)
                </p>
                <div class="sp-dtnews-main clearfix">
                    @Html.Raw(Model.Detail)
                </div>
                <div class="sp-dtnews-fbcmt">
                    <div class="social">
                        <span class="Facebook">
                            <span class="fb-like" data-href="@Web365Utility.ConfigWeb.Domain/tin-tuc/@Model.TitleAscii" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></span>
                        </span>
                        <span class="google">
                            <g:plusone size="medium" href="@Web365Utility.ConfigWeb.Domain/tin-tuc/@Model.TitleAscii"></g:plusone>
                        </span>
                    </div>
                    <div class="fb-comments" data-href="@Web365Utility.ConfigWeb.Domain/tin-tuc/@Model.TitleAscii" data-width="100%" data-numposts="5"></div>
                </div>
            </div>
        </div>
        <!--LEFT-->
        @Html.Action("MenuRight", "Layout")
        <!--RIGHT-->
    </div>
</div>
</div>
@section scripts
{
    <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
}

Web365/Views/News/Promotion.cshtml
@{
    ViewBag.Title = "Khuyến mại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="sp-header-bot">
    <div class="container">
        <h1 class="sp-hbot-tit">Khuyến mại</h1>
    </div>
</div>
<div class="sp-main">
    <div class="container">
        <div class="row">
            @Html.Action("ListPromotion", "News", new { page = ViewBag.Page })
            <!--LEFT-->
            @Html.Action("MenuRight", "Layout")
            <!--RIGHT-->
        </div>
    </div>
</div>

Web365/Views/News/PromotionDetail.cshtml
@using System.Globalization
@model Web365Domain.ArticleItem

@{
    ViewBag.Title = Model.SEOTitle;
    ViewBag.Description = Model.SEODescription;
    ViewBag.Keywords = Model.SEOKeyword;
    ViewBag.Image = Web365Utility.Web365Utility.GetPathPicture(Model.Picture.FileName);
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="sp-header-bot">
    <div class="container">
        <h1 class="sp-hbot-tit">Khuyến mại</h1>
    </div>
</div>
<div class="sp-main">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-xs-12">
                <div class="sp-bread">
                    <ul>
                        <li><a href="/">Trang chủ</a></li>
                        <li class="active"><a href="/khuyen-mai" title="Khuyến mại">Khuyến mại</a></li>
                    </ul>
                </div>
                <div class="sp-dtnews-main">
                    <h1 class="sp-dtnews-mname">@Model.Title</h1>
                    <p class="sp-dtnews-time">
                        @(Model.DateCreated != null
                                                    ? Model.DateCreated.Value.ToString("dd/MM/yyyy, hh:mm", CultureInfo.InvariantCulture)
                                                    : string.Empty)
                    </p>
                    <div class="sp-dtnews-main clearfix">
                        @Html.Raw(Model.Detail)
                    </div>
                    <div class="sp-dtnews-fbcmt">
                        <div class="social">
                            <span class="Facebook">
                                <span class="fb-like" data-href="@Web365Utility.ConfigWeb.Domain/khuyen-mai/@Model.TitleAscii" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></span>
                            </span>
                            <span class="google">
                                <g:plusone size="medium" href="@Web365Utility.ConfigWeb.Domain/khuyen-mai/@Model.TitleAscii"></g:plusone>
                            </span>
                        </div>
                        <div class="fb-comments" data-href="@Web365Utility.ConfigWeb.Domain/khuyen-mai/@Model.TitleAscii" data-width="100%" data-numposts="5"></div>
                    </div>
                </div>
            </div>
            <!--LEFT-->
            @Html.Action("MenuRight", "Layout", new {isPromotion = true})
            <!--RIGHT-->
        </div>
    </div>
</div>
@section scripts
{
    <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
}